### ISSUE TITLE
Error while deploying the application to Cloud Foundry

### ISSUE THREAD

**Issue by DeepakramKG** [IBM/order_processing_during_pandemics#2]
Hi,
I am an amateur to IBM cloud services. I followed the exact steps given in the Read me file. When I tried to deploy the application in IBM Cloud Foundry (Step 7), I am getting an error message saying that **you have exceeded your organization's memory limit**. 

I have attached a screenshot capturing the error message. Let me know how I can make this work. 

![Screenshot 2020-09-14 053141](https://user-images.githubusercontent.com/63659778/93031922-1e07da80-f64c-11ea-9863-280287145d5c.png)

**Comment by RahulReddyRavipally** [comment]
Hi,

Replace the manifest.yml(https://github.com/IBM/offline_order_processing_during_pandemics/blob/master/manifest.yml) content with the following content and repeat step 7.
```
applications:
 - name: order-processing-pandemic
   random-route: true
   memory: 512M
```

Thank You
